# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20160820_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='timestamp'),
        ),
    ]
